import Head from "next/head";
import { Inter } from "next/font/google";
import Carousel from "@/components/Carousel";
import Footer from "@/components/Footer";
import Meal from "@/components/Meal";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ meals }) {
  
   return (
      <>
         <Head>
            <title>Meals DB Home Page</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Carousel></Carousel>
         <main>
            <h2 className="my-10 text-3xl underline uppercase font-bold  text-blue-500  text-center ">
               Our Best Meals{" "}
            </h2>
            <div className="grid grid-cols-3 gap-5 gap-y-10 p-10">
               {meals?.slice(0, 6).map((meal) => (
                  <Meal key={meal.idMeal} meal={meal}></Meal>
               ))}
            </div>
            <div className="flex items-center justify-center mb-10">
               <Link href="/meals">
                  <button className="btn btn-primary text-white ">
                     show more
                  </button>
               </Link>
            </div>
         </main>
         <Footer></Footer>
      </>
   );
}
export const getServerSideProps = async() => {
   const res = await fetch('https://www.themealdb.com/api/json/v1/1/search.php?f=s'); 
   const data = await res.json(); 

   return {
      props: {
         meals: data.meals, 
      }
   }
}
